name = "invent2025"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Pages Functions configuration is implicit in directory structure,
# but we need to bind the D1 database.

[[d1_databases]]
binding = "DB"
database_name = "license-db"
database_id = "e2948956-0582-4a57-b26f-a04a123ba14c"
preview_database_id = "DB"
